[build]
  command = "npm run build"
  publish = "build"
  environment = { NODE_VERSION = "18.13.0" }
 
[dev]
 command = "vite dev"
 
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"